/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;

import javax.swing.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author User
 */
public class AddProgramForm extends javax.swing.JFrame {

    /**
     * Creates new form AddProgramForm
     */
    JFrame parentFrame;
    Controller con = new Controller();
    public AddProgramForm(JFrame j) {
        initComponents();
        parentFrame = j;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descriptionJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        durationJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nameJTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        durationJTextPane = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        deskriptionJTextPane = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        categoryJTextPane = new javax.swing.JTextPane();
        addProgramjButton = new javax.swing.JButton();
        addProgramjButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setName("AddProgramForm"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        descriptionJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descriptionJLabel.setText("Описание программы:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Дабавление программы обучения");

        nameJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameJLabel.setText("Название программы:");

        categoryLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        categoryLabel.setText("Категория:");

        durationJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        durationJLabel.setText("Длительность:");

        jScrollPane2.setViewportView(nameJTextPane);

        jScrollPane3.setViewportView(durationJTextPane);

        jScrollPane4.setViewportView(deskriptionJTextPane);

        jScrollPane5.setViewportView(categoryJTextPane);

        addProgramjButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addProgramjButton.setText("Добавить");
        addProgramjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProgramjButtonActionPerformed(evt);
            }
        });

        addProgramjButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addProgramjButton1.setText("Вернутся");
        addProgramjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProgramjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descriptionJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameJLabel)
                                    .addComponent(durationJLabel)
                                    .addComponent(categoryLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(addProgramjButton)
                        .addGap(18, 18, 18)
                        .addComponent(addProgramjButton1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)
                        .addComponent(nameJLabel))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descriptionJLabel)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(durationJLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(categoryLabel)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProgramjButton)
                    .addComponent(addProgramjButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addProgramjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProgramjButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        parentFrame.setVisible(true);
    }//GEN-LAST:event_addProgramjButton1ActionPerformed

    private void addProgramjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProgramjButtonActionPerformed
        if(con.addNewProgramCheckAccept(nameJTextPane.getText(), deskriptionJTextPane.getText(), durationJTextPane.getText(),
                categoryJTextPane.getText())) {


            if (con.addNewProgram(nameJTextPane.getText(), deskriptionJTextPane.getText(), durationJTextPane.getText(), categoryJTextPane.getText())) {
                JOptionPane.showMessageDialog(this, "Программа успешно добален");

            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Заполниет все поля", "Ошибка" , JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addProgramjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProgramjButton;
    private javax.swing.JButton addProgramjButton1;
    private javax.swing.JTextPane categoryJTextPane;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel descriptionJLabel;
    private javax.swing.JTextPane deskriptionJTextPane;
    private javax.swing.JLabel durationJLabel;
    private javax.swing.JTextPane durationJTextPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextPane nameJTextPane;
    // End of variables declaration//GEN-END:variables
}
